### PR TITLE
Release02

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Comment by xrotwang** [comment]
So this will require a release of lingrex, and possibly one of cldfviz, to then plot the figures with it, right?

**Comment by LinguList** [comment]
Yes.

**Comment by LinguList** [comment]
So we may also wait with those two. Just thought I already post what I have.

**Comment by LinguList** [comment]
I suggest I do the re-release of lingrex this morning. There's not more to add by now.

**Comment by xrotwang** [comment]
can do, too.

**Comment by xrotwang** [comment]
Have you pushed everything?

**Comment by LinguList** [comment]
Not the CLDF, should I do this as well? I thought we better recreate later with the new libraries?

**Comment by LinguList** [comment]
Or are you missing something else?

**Comment by xrotwang** [comment]
Ah, I was talking about lingrex

**Comment by LinguList** [comment]
Will check.

**Comment by LinguList** [comment]
Shall we merge already?

**Comment by xrotwang** [comment]
fine with me

**Pull request merged**
